# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 426)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 0, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 131, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cb_numbers = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_numbers.setGeometry(QtCore.QRect(70, 120, 181, 21))
        self.cb_numbers.setObjectName("cb_numbers")
        self.cb_alfabet = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_alfabet.setGeometry(QtCore.QRect(70, 150, 181, 21))
        self.cb_alfabet.setObjectName("cb_alfabet")
        self.btn_generator = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generator.setGeometry(QtCore.QRect(140, 210, 141, 31))
        self.btn_generator.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.btn_generator.setStyleSheet("border-radius: 5px;\n"
"background: #fffff;\n"
"border: 1px solid #141c21\n"
"")
        self.btn_generator.setAutoDefault(False)
        self.btn_generator.setObjectName("btn_generator")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 432, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Генератор паролів"))
        self.label_2.setText(_translate("MainWindow", "Тут буде результат"))
        self.cb_numbers.setText(_translate("MainWindow", "    Використовувати числа"))
        self.cb_alfabet.setText(_translate("MainWindow", "    Використовувати алфавіт"))
        self.btn_generator.setText(_translate("MainWindow", "Сгенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
